### ISSUE TITLE
Improve user experience by adding support for streaming transmission in chat mode

### ISSUE THREAD

**Issue by dbian** [qgrail/obsidian-ai-assistant#11]
Dear **qgrail**,

I am writing to express my appreciation for the hard work and dedication put into developing this plugin. As an avid user of this plugin, I have noticed that it has greatly enhanced my experience. However, I believe there is still room for improvement.

Specifically, I would like to suggest implementing support for stream-based data transfer within the plugin. By doing so, we can further enhance the user experience and make our interactions even smoother.

Thank you for taking the time to consider my suggestion. I look forward to seeing what improvements you have in store for us in the future.

Best regards,
_dbian_

**Comment by qgrail** [comment]
Hi @dbian,
Thank you for your feedback about the plugin. I am glad you like it.
Indeed, I also believe that stream mode will improve the user experience. I have been working on it, and I will release it soon. 
Best.

**Comment by qgrail** [comment]
Streaming is available in chat mode with the new 1.2.0 release.
Hope you will like it!
Best

**Comment by dbian** [comment]
Fantastic work @qgrail
