### ISSUE TITLE
Feature Request : Option to *not* replace selected text

### ISSUE THREAD

**Issue by laffan** [qgrail/obsidian-ai-assistant#15]
Thank you so much for making this!  Working great right out of the box.

Like most people I know, I never want to _fully_ hand over the reigns to ChatGPT, and would love the ability to to have it engage with selected text somehow and then produce results after the text, rather than replacing it. Best of all might be to wrap the generated text in a span that allows me accept/reject the results.  With this small change I think you could go a long way towards getting some of the best parts of https://www.notion.so/product/ai .

**Comment by qgrail** [comment]
Hey @laffan, thank you for your comment.
The option *not* to replace selected text when using the prompt command is available in the settings: under **Prompt behaviour**, you can deactivate **replace selection**. The answer will be pasted directly in your note after the selection.
