### ISSUE TITLE
Which OpenAI offer ?

### ISSUE THREAD

**Issue by tnntwister** [qgrail/obsidian-ai-assistant#23]
Hi, 

i have a paid subscription for OpenIA (ChatGPT Plus), can i use a model without paying for inscreasing usage limits ?

thank you !

**Comment by qgrail** [comment]
Hi, 
Unfortunately no. You need to get access to the API and ChatGPT plus does not includes it. (See [here](https://help.openai.com/en/articles/7039783-how-can-i-access-the-chatgpt-api).)
