### ISSUE TITLE
Any plans to support Anthropic API as an option?

### ISSUE THREAD

**Issue by afalk42** [qgrail/obsidian-ai-assistant#24]
I've found myself recently switching from GPT-4 to Claude 3 for all the work I do, because the answers from their latest "Opus" model are outperforming anything I was previously getting from OpenAI using GPT-4. 
Do you have any plans of supporting the Anthropic API in your plug-in for a future version? I would assume the same approach, with the user having to provide an API key to use the model...

**Comment by qgrail** [comment]
Hi @afalk42,
Thanks for your interest, yes, I am working on Claude integration. Will release it soon.

**Comment by afalk42** [comment]
That's awesome! If you need a beta tester, let me know!

Also, do you have a "Buy Me A Coffee" or similar link where I could send
you a little token of appreciation for this wonderful plugin?

Best Regards,

Alexander Falk
https://alexander.falk.us
https://xmlaficionado.com

Co-Founder, President, CEO - Altova <https://www.altova.com/>

WASH Major Gifts Initiative Adviser 2024-27 - Rotary Foundation
<https://www.rotary.org/en/about-rotary/rotary-foundation>
Past District Governor 2022-23,
District Rotary Foundation Chair 2024-27 - Rotary District 7930
<https://rotary7930.org/>
Past President 2018-19 - Marblehead Rotary Club
<https://www.marbleheadrotary.com/>



__________________________

https://fa.lk/personalemailpolicy
